=== GabrielaKopalova/Receptar/gabriela_kopalova.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="receptar">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="zakladni-nastaveni">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="jazyk" type="xs:string" />
              <xs:element name="charset" type="xs:string" />
              <xs:element name="javascript" type="xs:boolean" />
              <xs:element name="bez-stylu" type="xs:boolean" />
              <xs:element name="debug-mode" type="xs:boolean" />
              <xs:element name="maximalni-odezva">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:unsignedShort">
                      <xs:attribute name="jednotka" type="xs:string" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="nastaveni-receptu">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="zobrazovat" type="xs:boolean" />
                    <xs:element name="hodnoceni" type="xs:boolean" />
                    <xs:element name="komentovat" type="xs:boolean" />
                    <xs:element name="upravit" type="xs:boolean" />
                    <xs:element maxOccurs="unbounded" name="sdileni">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:boolean">
                            <xs:attribute name="domena" type="xs:string" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="todo-list" type="xs:boolean" />
                    <xs:element name="pridat-novy" type="xs:boolean" />
                    <xs:element name="mazani-vlastnich" type="xs:boolean" />
                    <xs:element name="mazani" type="xs:boolean" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="protokol" type="xs:string" />
              <xs:element name="kontakt-spravce" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="tabulka-prav">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="osoba">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="zobrazovat" type="xs:boolean" />
                    <xs:element name="hodnoceni" type="xs:boolean" />
                    <xs:element name="komentovat" type="xs:boolean" />
                    <xs:element name="upravit" type="xs:boolean" />
                    <xs:element maxOccurs="unbounded" name="sdileni">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:boolean">
                            <xs:attribute name="domena" type="xs:string" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="todo-list" type="xs:boolean" />
                    <xs:element name="pridat-novy" type="xs:boolean" />
                    <xs:element name="mazani-vlastnich" type="xs:boolean" />
                    <xs:element name="mazani" type="xs:boolean" />
                  </xs:sequence>
                  <xs:attribute name="typ" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="seznam-receptu">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="recept">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nazev" type="xs:string" />
                    <xs:element name="kuchyne" type="xs:string" />
                    <xs:element name="chod" type="xs:string" />
                    <xs:element name="doba-pripravy">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="jednotka" type="xs:string" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="suroviny">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="ingredience">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="mnozstvi" type="xs:string" use="required" />
                                  <xs:attribute name="jednotka" type="xs:string" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="postup" type="xs:string" />
                    <xs:element name="obrazek">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="odkaz" type="xs:string" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="komentare">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="komentar">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="autor" type="xs:string" use="required" />
                                  <xs:attribute name="cas" type="xs:time" use="required" />
                                  <xs:attribute name="datum" type="xs:date" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:unsignedInt" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="jazyk">
    <xs:restriction base="xs:string">
      <xs:enumeration value="czech"/>
      <xs:enumeration value="english"/>
      <xs:enumeration value="german"/>
      <xs:enumeration value="russian"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="charset">
    <xs:restriction base="xs:string">
      <xs:enumeration value="iso-8859-2"/>
      <xs:enumeration value="windows-1258"/>
      <xs:enumeration value="utf-8"/>
    </xs:restriction>
  </xs:simpleType> 
  <xs:simpleType name="protokol">
    <xs:restriction base="xs:string">
      <xs:enumeration value="http"/>
      <xs:enumeration value="https"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="kontakt-spravce">
    <xs:restriction base="xs:string">
       <xs:pattern value="[^@]+@[^\.]+\..+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== GabrielaKopalova/Receptar/gabriela_kopalova.xml
<?xml version="1.0" encoding="utf-8"?> 
    <?xml-stylesheet type="text/xsl" href="gabriela_kopalova.xsl"?>

<receptar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gabriela_kopalova.xsd">
    <zakladni-nastaveni>
        <jazyk>CZ</jazyk>
        <charset>utf-8</charset>
        <javascript>1</javascript>
        <bez-stylu>1</bez-stylu>
        <debug-mode>1</debug-mode>
        <maximalni-odezva jednotka="ms">3000</maximalni-odezva>
        <nastaveni-receptu>
            <zobrazovat>1</zobrazovat>
            <hodnoceni>1</hodnoceni>
            <komentovat>1</komentovat>
            <upravit>1</upravit>
            <sdileni domena="twitter">1</sdileni>
            <sdileni domena="facebook">1</sdileni>
            <sdileni domena="email">1</sdileni>
            <todo-list>1</todo-list>
            <pridat-novy>1</pridat-novy>
            <mazani-vlastnich>1</mazani-vlastnich>
            <mazani>1</mazani>
        </nastaveni-receptu>
        <protokol>http</protokol>
        <kontakt-spravce>sprava@receptar.cz</kontakt-spravce>
    </zakladni-nastaveni>

    <tabulka-prav>
        <osoba typ="neprihlaseny">
            <zobrazovat>1</zobrazovat>
            <hodnoceni>1</hodnoceni>
            <komentovat>0</komentovat>
            <upravit>0</upravit>
            <sdileni domena="twitter">1</sdileni>
            <sdileni domena="facebook">1</sdileni>
            <sdileni domena="email">1</sdileni>
            <todo-list>0</todo-list>
            <pridat-novy>0</pridat-novy>
            <mazani-vlastnich>0</mazani-vlastnich>
            <mazani>0</mazani>
        </osoba>
        <osoba typ="prihlaseny">
            <zobrazovat>1</zobrazovat>
            <hodnoceni>1</hodnoceni>
            <komentovat>1</komentovat>
            <upravit>1</upravit>
            <sdileni domena="twitter">1</sdileni>
            <sdileni domena="facebook">1</sdileni>
            <sdileni domena="email">1</sdileni>
            <todo-list>1</todo-list>
            <pridat-novy>1</pridat-novy>
            <mazani-vlastnich>1</mazani-vlastnich>
            <mazani>0</mazani>
        </osoba>
        <osoba typ="administrator">
            <zobrazovat>1</zobrazovat>
            <hodnoceni>1</hodnoceni>
            <komentovat>1</komentovat>
            <upravit>0</upravit>
            <sdileni domena="twitter">1</sdileni>
            <sdileni domena="facebook">1</sdileni>
            <sdileni domena="email">1</sdileni>
            <todo-list>1</todo-list>
            <pridat-novy>1</pridat-novy>
            <mazani-vlastnich>1</mazani-vlastnich>
            <mazani>1</mazani>
        </osoba>
    </tabulka-prav>
    
    <seznam-receptu>
        <recept id="1">
            <nazev>Rychlé boloňské špagety</nazev>
            <kuchyne>Italská kuchyně</kuchyne>
            <chod>Hlavní chod</chod>
            <doba-pripravy jednotka="min">45</doba-pripravy>
            <suroviny>
                <ingredience mnozstvi="500" jednotka="g">špagety</ingredience>
                <ingredience mnozstvi="3" jednotka="lzice">olivový olej</ingredience>
                <ingredience mnozstvi="500" jednotka="g">vepřové mleté maso</ingredience>
                <ingredience mnozstvi="5" jednotka="g">sůl</ingredience>
                <ingredience mnozstvi="5" jednotka="g">pepř</ingredience>
            </suroviny>
            <postup>Na pánvi rozehřejeme oliv. olej a zpěníme na něm nadrobno nakrájenou cibuli dozlatova. Poté přidáme nasekaný česnek a minutku restujeme. ...</postup>
            <obrazek odkaz="https://www.albert.cz/imgm/YTE4ODMtd2lkZUFyZWF8YTkwNDM4fGE0ODA0fGE3MTYyM02Mqxg/103491.jpg">obrázek boloňských špaget s bazalkou a parmesánem navrchu.</obrazek>
            <komentare>
                <komentar autor="Karel" cas="15:30:10" datum="2016-10-05">Musím doporučit, nejlepší recept co jsem si v poslední době uvařil.</komentar>
                <komentar autor="Pepa" cas="23:59:16" datum="2016-09-09">Obecně dobré jídlo, né však pro vegetariány.</komentar>
            </komentare>  
        </recept>
        
        <recept id="2">
            <nazev>Bramboračka</nazev>
            <kuchyne>Česká kuchyně</kuchyne>
            <chod>Polévka</chod>
            <doba-pripravy jednotka="h">1</doba-pripravy>
            <suroviny>
                <ingredience mnozstvi="8" jednotka="ks">brambory</ingredience>
                <ingredience mnozstvi="5" jednotka="ks">hříbky</ingredience>
                <ingredience mnozstvi="4" jednotka="l">voda</ingredience>
                <ingredience mnozstvi="1" jednotka="ks">bobkový list</ingredience>
            </suroviny>
            <postup>Houby namočíme na 20 min do vody. Zeleninu očistíme, oloupeme, nakrájíme, brambory na větší kostky. ...</postup>
            <obrazek odkaz="http://www.menudomu.cz/wp-content/uploads/2013/01/brambora%C4%8Dka-4.jpg">Servírovaná bramboračka</obrazek>
            <komentare>
                <komentar autor="Petr" cas="17:33:01" datum="2016-05-10"></komentar>
            </komentare>  
        </recept>
        
        <recept id="3">
            <nazev>Nachos s kuřecím masem</nazev>
            <kuchyne>Mexická kuchyně</kuchyne>
            <chod>Předkrm</chod>
            <doba-pripravy jednotka="min">15</doba-pripravy>
            <suroviny>
                <ingredience mnozstvi="150" jednotka="g">Tortilla Chips Natural</ingredience>
                <ingredience mnozstvi="50" jednotka="g">strouhany čedar</ingredience>
                <ingredience mnozstvi="400" jednotka="g">černé fazole</ingredience>
            </suroviny>
            <postup>Tortillové chipsy rozprostřeme na zapékací mísu a navrstvíme na ní ingredience kromě zakysané smetany. ...</postup>
            <obrazek odkaz="http://st2.depositphotos.com/1998601/11559/i/450/depositphotos_115593522-stock-photo-nachos-with-chicken-and-vegetables.jpg">Nachos s kuřecím masem servírované s dresinkem</obrazek>
            <komentare>
                <komentar autor="Adam" cas="22:44:51" datum="2017-02-08">Díky za recept, fakt výborné, celá rodina si pochutnala.</komentar>
            </komentare>  
        </recept>
        
        <recept id="4">
            <nazev>Mandarinkový salát s mrkví</nazev>
            <kuchyne>Čínská kuchyně</kuchyne>
            <chod>Salát</chod>
            <doba-pripravy jednotka="min">20</doba-pripravy>
            <suroviny>
                <ingredience mnozstvi="5" jednotka="ks">mandarinka</ingredience>
                <ingredience mnozstvi="2" jednotka="svazek">ředkvičky</ingredience>
                <ingredience mnozstvi="2" jednotka="ks">mrkev</ingredience>
            </suroviny>
            <postup>Ředkvičky a mrkve očistíme. Mrkve nastrouháme najemno a ředkvičky nakrájíme na plátky, ...</postup>
            <obrazek odkaz="http://st.depositphotos.com/1000185/4104/i/950/depositphotos_41040793-stock-photo-salad.jpg">Salát s mrkví, mandarinkou, sezamu a petrželkou</obrazek>
            <komentare>
                <komentar autor="Eva" cas="11:47:33" datum="2016-05-01">Velice rychlý, chutný a lehký salát.</komentar>
            </komentare>  
        </recept>
        
        <recept id="5">
            <nazev>Chutné řecké brambory</nazev>
            <kuchyne>Řecká kuchyně</kuchyne>
            <chod>Příloha</chod>
            <doba-pripravy jednotka="h">1,5</doba-pripravy>
            <suroviny>
                <ingredience mnozstvi="2" jednotka="lzice">dobromysl</ingredience>
                <ingredience mnozstvi="1,5" jednotka="kg">brambory</ingredience>
                <ingredience mnozstvi="2" jednotka="lzice">čerstvý tymián</ingredience>
            </suroviny>
            <postup>Oškrábané brambory podélně nakrájíme na osminky a vyložíme na plech. Brambory osolíme a okořeníme dobromyslí s tymiánem, ...</postup>
            <obrazek odkaz="https://www.vareni.cz/include/ir/recepty/40295/zdet--mm670xmm600.jpg"></obrazek>
            <komentare>
                <komentar autor="Adéla" cas="09:33:21" datum="2016-02-05">Skvělé brambory na řecký způsob. Recept na bramborovou přílohu k různým masům a omáčkám.</komentar>
            </komentare>  
        </recept>      
    </seznam-receptu>
</receptar>
